version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: my-sql-server
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: grhapp
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  spring-backend:
    image: khadijabenali/backdockerimage:tag123
    container_name: spring-backend
    depends_on:
      - db
    ports:
      - '8090:8090'
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/grhapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  web:
    image: khadijabenali/frontdockerimage:tag6
    container_name: frontend-web
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: